name: Scrape Images

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:       # bisa manual trigger juga

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-slugify

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images/
          git commit -m "Update scraped images $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
